complexity:
  ComplexCondition:
    threshold: 6
  LongParameterList:
    # Spring DI can be a bit much
    constructorThreshold: 100
  CyclomaticComplexMethod:
    threshold: 17
  NestedBlockDepth:
    threshold: 6
style:
  MaxLineLength:
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
    # Image commands are urls possibly followed by a comment, so they get long
    excludes: ['**/commands/image/**']
  ReturnCount:
    active: false
  MagicNumber:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
libraries:
  ForbiddenPublicDataClass:
    active: false
  LibraryEntitiesShouldNotBePublic:
    active: false
